"""gallery_html.py — write a browsable one-page HTML index of the gallery.

Called by examples/gallery.py after rendering; can also run standalone:
    python examples/gallery_html.py
"""

from __future__ import annotations

from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "docs" / "images"


def write_html_index(charts: dict, out_dir: Path | None = None) -> Path:
    """Write docs/gallery.html — one lazy-loading card per chart image."""
    import html as _html

    out_dir = out_dir or OUT.parent
    rows = []
    for name in charts:
        safe = _html.escape(name)
        rows.append(
            f'<figure><a href="images/{safe}.png" target="_blank">'
            f'<img src="images/{safe}.png" loading="lazy" alt="{safe}">'
            f"</a><figcaption>{safe}</figcaption></figure>"
        )
    doc = (
        '<!DOCTYPE html>\n<html lang="en">\n<head>\n'
        '<meta charset="utf-8">\n'
        "<title>Math Modeling Viz - Chart Gallery</title>\n"
        "<style>"
        "body{font-family:system-ui,sans-serif;margin:24px;background:#FAFAFA}"
        "h1{margin-bottom:4px}p.sub{color:#666;margin-top:0}"
        ".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:16px}"
        "figure{margin:0;background:#fff;border:1px solid #E5E5E5;border-radius:8px;"
        "padding:10px;box-shadow:0 1px 3px rgba(0,0,0,.06)}"
        "img{width:100%;height:auto;border-radius:4px}"
        "figcaption{font-size:13px;color:#444;margin-top:6px;text-align:center}"
        "</style>\n</head>\n<body>\n"
        "<h1>Math Modeling Viz - Chart Gallery</h1>\n"
        '<p class="sub">Regenerated by <code>examples/gallery.py</code> - '
        "every image is produced by the library itself.</p>\n"
        f'<div class="grid">\n{chr(10).join(rows)}\n</div>\n'
        "</body>\n</html>\n"
    )
    target = out_dir / "gallery.html"
    target.write_text(doc, encoding="utf-8")
    print(f"  gallery.html written ({len(charts)} figures)")
    return target


if __name__ == "__main__":
    import sys

    sys.path.insert(0, str(Path(__file__).resolve().parent))
    # reuse the chart dict from gallery.py without re-rendering
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "gallery", Path(__file__).resolve().parent / "gallery.py")
    gallery = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(gallery) if False else None
    from gallery import charts

    write_html_index(charts)
